# Generated by Django 5.2.5 on 2025-12-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routefinder', '0002_contribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('report_type', models.CharField(choices=[('harassment', 'Harassment'), ('safety_hazard', 'Safety Hazard'), ('staff_behaviour', 'Staff Behaviour'), ('cleanliness', 'Cleanliness'), ('other', 'Other')], max_length=50)),
                ('priority_level', models.IntegerField(choices=[(1, 'Critical - Harassment'), (2, 'High - Safety Hazard'), (3, 'Medium - Staff Behaviour'), (4, 'Low - Cleanliness'), (5, 'Low - Other')])),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['priority_level', '-date'],
            },
        ),
    ]
